- name: install socat
  pkgng:
    name: socat
    state: latest

- name: install haproxy
  pkgng:
    name: haproxy18
    state: latest

- name: copy haproxy config
  copy: src=haproxy.conf dest=/usr/local/etc/haproxy.conf owner=root mode=0644
  notify: haproxy reload

- name: enable haproxy at startup
  service: name=haproxy state=started enabled=yes
  register: service_state

