all:
  children:
    haproxy:
      hosts:
        COVID-19-HA:
          ansible_host: 172.16.21.16
    openvpn:
      hosts:
        COVID-19-01:
          ansible_host: 172.16.21.17
          network: 172.16.86.0
        COVID-19-02:
          ansible_host: 172.16.21.18
          network: 172.16.87.0
  vars:
    ansible_ssh_user: root
    ansible_ssh_pass: rootpass
    pkg_proxy: ""
